version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: sportdb
      POSTGRES_USER: sportuser
      POSTGRES_PASSWORD: sportpass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
